name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          npm test

      - name: Run npm audit
        run: |
          npm audit --json > npm-audit.json

      - name: Install Snyk
        run: |
          npm install -g snyk

      - name: Test for vulnerabilities using Snyk
        run: |
          snyk test --all-projects

      - name: Docker build
        run: |
          docker build -t my-secure-app .

      - name: Log in to AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

      - name: Push Docker image to ECR
        run: |
          docker tag my-secure-app:latest ${{ 982081044632 }}.dkr.ecr.us-east-1.amazonaws.com/my-secure-app:latest
          docker push ${{ 982081044632 }}.dkr.ecr.us-east-1.amazonaws.com/my-secure-app:latest

      - name: Deploy to ECS Fargate
        run: |
          aws ecs update-service \
            --cluster my-secure-cluster \
            --service my-secure-app-service \
            --force-new-deployment

